language: node_js

notifications:
  email: false

node_js:
  - '8'

script:
  - npm run build-docs

branches:
  only:
    - master

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $CI_TOKEN # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
