version: "3"
services:
  vue2react: #项目的service name
    container_name: "vue2react-container" #容器名称
    image: nginx #指定镜像
    restart: always
    ports:
      - 81:80
    volumes:
      #~ ./nginx.conf为宿主机目录, /etc/nginx为容器目录
      - ./nginx.conf:/etc/nginx/nginx.conf #挂载nginx配置
      #~ ./dist 为宿主机 build 后的dist目录, /usr/share/nginx/html为容器目录,
      - ./dist:/usr/share/nginx/html/ #挂载项目
    privileged: true
